<?php

/**
 * @file
 * Exercise 1 module.
 *
 * Create a table that displays on the homepage displaying table of users that is returned
 * from https://deelay.me/5000/https://jsonplaceholder.typicode.com/users.
 */

/**
 * Implements hook_cron().
 */
function exercise1_cron() {
  // Fetch the list of users from provided JSON API URL and put it to Drupal State API.
  \Drupal::state()->set('exercise1.users', json_decode(file_get_contents('https://deelay.me/5000/https://jsonplaceholder.typicode.com/users')));
}
